@startuml

actor at as "Atendente"
participant sist as "Sistema"
participant banco as "Banco de Dados"

at->sist: iniciarEmprestimo(id_leitor)

sist->banco: Busca leitor por id

banco->sist: Retorna leitor

sist->banco: Insere registros empréstimo e devolução

banco->sist: Retorna registros empréstimo e devolução

sist->at: Retorna mensagem de sucesso

@enduml

