@startuml

actor at as "Atendente"
participant sist as "Sistema" 
participant banco as "Banco de Dados" 

at->sist: Solicita encerrar emprestimo

sist->banco: Busca LinhaDoEmprestimo com situação "Emprestada"

banco->sist: Retorna LinhaDoEmprestimo

sist->banco: Atualiza LinhaDoEmprestimo com situação "Vigente"

banco->sist:

@enduml
