@startuml

actor "Atendente" as A
actor "Sistema" as S
participant "Banco: Leitor" as L
participant "Banco: CopiaDoLivro" as C
participant "Banco: LinhaDoEmprestimo" as LE

A -> S : emprestarLivro(id_Livro)
activate S

S --> L : identificarLeitor()
activate L
L --> S : leitorIdentificado()
deactivate L

S -> C : verificarDisponibilidade()
activate C
C --> S : livroDisponivel()
deactivate C

S -> LE : criarLinhaDoEmprestimo()
activate LE
LE --> S : linhaCriada()
deactivate LE

S -> LE : associarAoLeitorEACopia()
activate LE
LE --> S : associacaoConcluida()
deactivate LE

S -> C : alterarSituacao("emprestada")
activate C
C --> S : situacaoAlterada()
deactivate C

S -> LE : calcularDataDevolucao()
activate LE
LE --> S : dataCalculada(data)
deactivate LE

S -> LE : armazenarDataDevolucao()
activate LE
LE --> S : dataArmazenada()
deactivate LE

S --> A : informaDataDevolucao()
deactivate S

@enduml
